import os

APPLICATION_NAME = "encoded_core"
APPLICATION_PYPROJECT_NAME = os.environ.get("APPLICATION_PYPROJECT_NAME") or "encoded_core"
os.environ["APPLICATION_PYPROJECT_NAME"] = APPLICATION_PYPROJECT_NAME
